name:                csv-parser
version:             0.1.0.0
github:              "githubuser/CSVParser"
license:             BSD3
author:              "Kaya Akagi"
maintainer:          "example@example.com"
copyright:           "2018 Kaya Akagi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/CSVParser#readme>

dependencies:
- base >= 4.7 && < 5
- text
- parsec
- conduit
- deepseq
- vector
- parallel
- template-haskell
- attoparsec
- containers
- unicode-show

library:
  source-dirs: src

executables:
  CSVParser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2

tests:
  CSVParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSVParser
